### ISSUE TITLE
OSx problems

### ISSUE THREAD

**Issue by smclinden** [ANSSI-FR/polichombr#106]
This is from a  fresh GIT installed.

**Comment by tpo-anssi** [comment]
Hi!
Do you have any more information? (ie where the import error is happening)

**Comment by smclinden** [comment]
Yes, when I run utils/db_create.py

Sean

----- Original Message -----

**Comment by tpo-anssi** [comment]
This could happen if you're not in the root directory, due to the module load mechanism in Python

**Comment by smclinden** [comment]
This is on OS X which has lots of problems with Python, but I am in the root of the polichombr distribution.

Sean



----- Original Message -----

**Comment by tpo-anssi** [comment]
Maybe you can try in your shell:
```
export `pwd`:$PYTHONPATH
```

**Comment by smclinden** [comment]
OK. Did that. Got:

Traceback (most recent call last):
  File "utils/db_create.py", line 2, in <module>
    from poli import db
  File "/Users/seanmclinden/polichombr/poli/__init__.py", line 50, in <module>
    app.register_blueprint(apiview)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/local/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/usr/local/lib/python2.7/site-packages/flask/blueprints.py", line 128, in wrapper
    func(state)
  File "/usr/local/lib/python2.7/site-packages/flask/blueprints.py", line 399, in <lambda>
    self.name, code_or_exception, f))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1090, in _register_error_handler
    'It is currently not possible to register a 500 internal ' \
AssertionError: It is currently not possible to register a 500 internal server error on a per-blueprint level.


Sean

----- Original Message -----

**Comment by tpo-anssi** [comment]
This should be fixed with #107 , could you test?

**Comment by smclinden** [comment]
That seems to have fixed it. 

Thanks!

Sean

----- Original Message -----

**Comment by tpo-anssi** [comment]
You're welcome!
Fixed by #107
