### ISSUE TITLE
AnalyzeIt.rb is broken

### ISSUE THREAD

**Issue by tpo-anssi** [ANSSI-FR/polichombr#137]
There is two problems

 * the encoding has been removed and metasm doesn't like it
 * There is a typo on line 948

Attached two stack traces.

```
analysis_tools/AnalyzeIt.rb:949:in `block in <main>': undefined local variable or method `egexStr' for main:Object (NameError)
```

```
polichombr/metasm/metasm/os/main.rb:165:in `index': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
polichombr/metasm/metasm/os/main.rb:165:in `index
from analysis_tools/AnalyzeIt.rb:757:in `block (2 levels) in <main>'
from analysis_tools/AnalyzeIt.rb:753:in `each'
from analysis_tools/AnalyzeIt.rb:753:in `block in <main>'
from analysis_tools/AnalyzeIt.rb:750:in `each'
from analysis_tools/AnalyzeIt.rb:750:in `<main>'
```

**Comment by tpo-anssi** [comment]
Fixed by #138
