### ISSUE TITLE
More explanation on create_db error please

### ISSUE THREAD

**Issue by iaeubanks** [ANSSI-FR/polichombr#194]
I am having the same issue with the poli module not being pulled. I am pretty sure that I am having more troubles trying to get the python path set up to work around this. 

Could I get some more help in this area? I understand that I can use the python path to make a work around to the root directory, but I have tried to do so and failed so I might need more detailed help. 

Please get back to me at your earliest convenience. Thank you!

**Comment by iaeubanks** [comment]
One of my problems could be the location of the Polichombr folder. Could you please let me know of a recommended location for the folder to be used?

**Comment by iaeubanks** [comment]
I was able to get this problem resolved by adding the python path:

Traceback (most recent call last):
File "./utils/db_create.py", line 14, in
from poli import app, db
ImportError: No module named poli

But now I am getting the following error as well. 

Traceback (most recent call last):
File "./db_)create.py", line 14, in <module>
from poli import app, db
File "/home/user/Downloads/polichombr-1.5/poli/__init__.py", line 10, in <module>
from flask import Flask, abort
ImportError: No module named flask

I fixed this error but now in the __init__.py of the markupsafe package, I am getting a syntax error for "def __html__(self) -> str:"

How would i fix this problem?
